/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 matebook.glb 
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/huawei-matebook-x-d3dcec6b451a41cf90a6e0a7c0474378
Title: HUAWEI MateBook X
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Notebook(props) {
  const { nodes, materials } = useGLTF('/models/matebook.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.714, 104.927, 103.248]} scale={142.841}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.diannao} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.diannao} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/matebook.glb')
